apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmsapi-deployment
  labels:
    app:  cmsapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  cmsapi-pod
  template:
    metadata:
      labels:
        app: cmsapi-pod
    spec:
      containers:
      - name: cmsapi-container
        image: dharmin/cmsapi:v1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80